name: Browser test build - parallel
on: push
jobs:
  Add-ToCart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
            command: npm run test:addToCart

      - name: Cypress Test Report - Add To Cart
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report new1
          path: cypress/reports/html

  Reg-Flow-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
       # Install npm dependencies, cache them correctly
       # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
            command: npm run test:register

      - name: Cypress Test Report - Reg Flow
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report new2
          path: cypress/reports/html

